export enum CAT_ICON {
  'Shopping' = 'shopping',
  'Bills' = 'bills',
  'Housing' = 'house',
  'Food' = 'eating',
  'Fuel' = 'gas',
  'Groceries' = 'groceries',
  'Healthcare' = 'health',
  'Internet' = 'internet',
  'Entertainment' = 'movies',
  'Travel' = 'plane',
  'Subscriptions' = 'stream',
  'Transportation' = 'taxi',
  'Fitness' = 'gym',
  'Other' = 'list',
  'Utilities' = 'utilities',
  'Shailendra' = 'user-male',
  'Tanya' = 'user-female',
}
